#add parrot drivers here
obj-y += char/
obj-y += power/
obj-y += net/
obj-y += usb/otg/
obj-y += usb/serial/blackberry/
obj-y += sound/soc/codecs/
obj-y += input/touchscreen/
obj-y += invensense/inv_mpu/
obj-y += i2c/

# Without this, built-in.o won't be created when it's empty, and the
# final vmlinux link will fail.
obj-y += dummy.o
