obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_LQ043T1DG01) += panel-sharp-lq043t1dg01.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-NL8048HL11-01B.o
obj-$(CONFIG_PANEL_TOSHIBA_LT104AC36100) += panel-toshiba.o

obj-$(CONFIG_PANEL_PICO_DLP) +=  panel-picodlp.o
obj-$(CONFIG_PANEL_TOPPOLY_TDO35S) += panel-toppoly-tdo35s.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o
obj-$(CONFIG_PANEL_SIL9022) += panel_sil9022.o
obj-$(CONFIG_PANEL_CHIMEI) += panel-chimei-LW500AC9004.o
obj-$(CONFIG_PANEL_CHIMEI) += panel-hannstar.o
obj-$(CONFIG_PANEL_LAJ07T001A) += panel-tpo-laj07t001a.o
obj-$(CONFIG_PANEL_LAJ07T001A) += panel-kyocera-TCG070WVLPAANN.o
obj-$(CONFIG_PANEL_KYOCERATCG101) += panel-kyocera-TCG101WXLPANNAN.o
